#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Reload D-Bus system bus
    if command -v systemctl >/dev/null 2>&1; then
        systemctl daemon-reload || true
        systemctl reload dbus || true
        systemctl enable kuhlerprofil.service || true
    fi
fi
exit 0
